#ifndef BACKCOLOR
#define BACKCOLOR
#pragma once

#include <Windows.h>

enum class BackColor : WORD {
	Black = 0x0000,
	DarkGray = BACKGROUND_INTENSITY,

	DarkBlue = BACKGROUND_BLUE,
	Blue = BACKGROUND_BLUE | BACKGROUND_INTENSITY,
	LightBlue = BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	Teal = BACKGROUND_BLUE | BACKGROUND_GREEN,

	DarkGreen = BACKGROUND_GREEN,
	LightGreen = BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	DarkYellow = BACKGROUND_GREEN | BACKGROUND_RED,
	Yellow = BACKGROUND_GREEN | BACKGROUND_RED | BACKGROUND_INTENSITY,

	DarkRed = BACKGROUND_RED,
	Red = BACKGROUND_RED | BACKGROUND_INTENSITY,
	Purple = BACKGROUND_RED | BACKGROUND_BLUE,
	Pink = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY,

	LightGray = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_GREEN,
	White = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY
};

#endif // BACKCOLOR