#ifndef TEXTCOLOR
#define TEXTCOLOR
#pragma once

#include <Windows.h>

enum class TextColor : WORD {
	Black = 0x0000,
	DarkGray = FOREGROUND_INTENSITY,

	DarkBlue = FOREGROUND_BLUE,
	Blue = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	LightBlue = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	Teal = FOREGROUND_BLUE | FOREGROUND_GREEN,

	DarkGreen = FOREGROUND_GREEN,
	LightGreen = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	DarkYellow = FOREGROUND_GREEN | FOREGROUND_RED,
	Yellow = FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY,

	DarkRed = FOREGROUND_RED,
	Red = FOREGROUND_RED | FOREGROUND_INTENSITY,
	Purple = FOREGROUND_RED | FOREGROUND_BLUE,
	Pink = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,

	LightGray = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN,
	White = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
};

#endif // TEXTCOLOR